### ISSUE TITLE
Quantil usage ?

### ISSUE THREAD

**Issue by Spouke4110** [ECheynet/polarPcolor#2]
In line 167 of your polarPcolor.m (caxis([quantile(Z(:),0.01),quantile(Z(:),0.99)]))), why did you use the 1% and 99% quantiles instead of the min and max? Just for my understanding, this function sets the min and max of the color scale, doesn't it (as in which color corresponds to which value)? I would assume that the quantile will skew your data if you have a wide range of values and a lot of data, which is the case in radar applications.

**Comment by Spouke4110** [comment]
Jep ok I get it. It is used so that high values do not drag down the entire scan.

**Comment by ECheynet** [comment]
Yes that is correct. This is a "trick" to avoid outliers distorting the results.
